import styles from "../styles/layoutG.module.css";
import "../styles/globals.css";

export const metadata = {
  title: "Valleir",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <div className={styles.page}>
          <main className={styles.main}>  
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
